#!/usr/bin/env python3
"""
FinanceAgent (Architecture 3.0) - Finance Squad
Inherits from BaseAgent and uses enterprise services for financial analysis.
"""
import json
from pathlib import Path
from ...base_agent import BaseAgent

class FinanceAgent(BaseAgent):
    """
    An enterprise-grade agent for financial analysis, fully integrated
    with the core services of the Autonomous Enterprise Builder.
    """
    
    def _prepare_prompt(self, prompt: str, context: dict) -> str:
        """
        Constructs a specialized, context-rich prompt for financial tasks
        by leveraging the Knowledge Engine and the agent's own state.
        """
        self.logger.info("Preparing prompt for financial analysis...")
        
        # --- 1. Leverage Agent State ---
        previous_analyses = self.get_state('completed_analyses', [])
        
        # --- 2. Leverage Knowledge Engine ---
        financial_context = ""
        if self.knowledge_engine:
            self.logger.info("Querying Knowledge Engine for financial context...")
            rag_query = f"financial modeling principles for {prompt[:50]}"
            # Use the integrated knowledge_query tool for consistency
            knowledge_tool = self.get_tool("knowledge_query")
            if knowledge_tool:
                results = knowledge_tool(query=rag_query, max_results=3)
                if results.get("success"):
                    financial_context = "\n".join([res['content'][:300] for res in results.get("results", [])])
        
        # --- 3. Load System Prompt from File ---
        try:
            prompt_path = Path(__file__).parent / "prompt.txt"
            with open(prompt_path, 'r') as f:
                system_prompt_template = f.read()
        except Exception as e:
            self.logger.error(f"Could not load prompt file: {e}")
            system_prompt_template = """You are a world-class Senior Financial Analyst Agent within a larger autonomous enterprise.

YOUR CAPABILITIES:
Skills: {skills}
Completed Analyses: {completed_analyses}

ENTERPRISE FINANCIAL STANDARDS:
- Adhere strictly to GAAP (Generally Accepted Accounting Principles)
- All analyses must include comprehensive risk assessments and mitigation strategies
- Financial projections must cover a 3-5 year period with clear assumptions
- All work must be grounded in real-world data retrieved from the enterprise Knowledge Engine

AVAILABLE CONTEXT:
[Retrieved Financial Knowledge]
{financial_knowledge_context}

[Memory of Previous Tasks]
{previous_context}

[Additional Context for Current Mission]
{additional_context}

YOUR CURRENT MISSION:
Task: {task}

INSTRUCTIONS:
1. Analyze the task and all available context
2. Formulate a professional, data-driven financial analysis or report
3. Structure your response clearly with sections for findings, projections, and recommendations
4. Return ONLY the raw text of your complete analysis"""

        # --- 4. Assemble the Final Prompt ---
        full_prompt = system_prompt_template.format(
            skills=', '.join(self.config.get('skills', [])),
            completed_analyses=len(previous_analyses),
            financial_knowledge_context=financial_context or "No specific context found.",
            previous_context=json.dumps(self.get_state('context_memory', {}), indent=2),
            additional_context=json.dumps(context, indent=2) if context else "None",
            task=prompt
        )
        
        return full_prompt

    def _process_response(self, response: str) -> dict:
        """
        Processes the raw LLM response into a structured financial report.
        """
        self.logger.info("Processing financial analysis response.")
        
        # Extract key components from response
        analysis_summary = response[:500] + "..." if len(response) > 500 else response
        
        result = {
            'agent_type': 'FinanceAgent',
            'task_id': f"task_{self.task_count}",
            'timestamp': self.last_activity.isoformat(),
            'summary': analysis_summary,
            'full_response': response,
            'analysis_type': 'comprehensive_financial_analysis',
            'recommendations': self._extract_recommendations(response),
            'risk_assessment': self._extract_risk_factors(response)
        }
        
        self._update_project_memory(result)
        
        # Use the file_write tool to save the report
        file_tool = self.get_tool("file_write")
        if file_tool:
            report_path = f"data/agent_outputs/finance_report_{self.task_count}.md"
            report_content = f"""# Financial Analysis Report
**Generated by**: FinanceAgent (Architecture 3.0)
**Task ID**: {result['task_id']}
**Timestamp**: {result['timestamp']}

## Executive Summary
{analysis_summary}

## Full Analysis
{response}

## Risk Assessment
{json.dumps(result['risk_assessment'], indent=2)}

## Recommendations
{json.dumps(result['recommendations'], indent=2)}
"""
            save_result = file_tool(path=report_path, content=report_content)
            if save_result.get('success'):
                self.logger.info(f"Financial report saved to {report_path}")
                result['report_path'] = report_path

        return result

    def _extract_recommendations(self, response: str) -> list:
        """Extract actionable recommendations from the analysis"""
        # Simple keyword-based extraction - could be enhanced with NLP
        recommendations = []
        lines = response.split('\n')
        
        for line in lines:
            if any(keyword in line.lower() for keyword in ['recommend', 'suggest', 'should', 'advise']):
                recommendations.append(line.strip())
        
        return recommendations[:5]  # Top 5 recommendations

    def _extract_risk_factors(self, response: str) -> dict:
        """Extract risk factors from the analysis"""
        risk_keywords = ['risk', 'threat', 'concern', 'challenge', 'volatility']
        risk_factors = []
        
        lines = response.split('\n')
        for line in lines:
            if any(keyword in line.lower() for keyword in risk_keywords):
                risk_factors.append(line.strip())
        
        return {
            'identified_risks': risk_factors[:3],
            'risk_level': 'medium',  # Could be determined by analysis
            'mitigation_required': len(risk_factors) > 0
        }

    def _update_project_memory(self, result: dict):
        """Updates the agent's persistent state with details of the completed task."""
        analyses = self.get_state('completed_analyses', [])
        analyses.append({
            'task_id': result['task_id'],
            'timestamp': result['timestamp'],
            'analysis_type': result['analysis_type']
        })
        
        # Keep a running history of the last 10 analyses
        if len(analyses) > 10:
            analyses = analyses[-10:]
            
        self.update_state('completed_analyses', analyses)
        self.update_state('total_analyses_completed', len(analyses))
        
        # Update context memory for future tasks
        context_memory = {
            'last_analysis_type': result['analysis_type'],
            'recent_recommendations': result['recommendations'][:2],
            'risk_awareness': result['risk_assessment']['risk_level']
        }
        self.update_state('context_memory', context_memory)
        
        self.logger.info(f"Agent memory updated. Total analyses completed: {len(analyses)}")
