#!/usr/bin/env python3
"""
PenetrationTester Agent (Architecture 3.0) - Cyber Security Squad
Enterprise-grade security testing and vulnerability assessment agent.
"""
import json
from pathlib import Path
from ...base_agent import BaseAgent

class PenetrationTester(BaseAgent):
    """
    An enterprise-grade agent for penetration testing and security assessment,
    fully integrated with the core services of the Autonomous Enterprise Builder.
    """
    
    def _prepare_prompt(self, prompt: str, context: dict) -> str:
        """
        Constructs specialized prompts for cybersecurity and penetration testing tasks.
        """
        self.logger.info("Preparing prompt for security assessment...")
        
        # --- 1. Leverage Agent State ---
        previous_assessments = self.get_state('completed_assessments', [])
        
        # --- 2. Leverage Knowledge Engine for Security Context ---
        security_context = ""
        if self.knowledge_engine:
            self.logger.info("Querying Knowledge Engine for security context...")
            rag_query = f"cybersecurity vulnerability assessment {prompt[:50]}"
            knowledge_tool = self.get_tool("knowledge_query")
            if knowledge_tool:
                results = knowledge_tool(query=rag_query, max_results=3)
                if results.get("success"):
                    security_context = "\n".join([res['content'][:300] for res in results.get("results", [])])
        
        # --- 3. Load System Prompt from File ---
        try:
            prompt_path = Path(__file__).parent / "prompt.txt"
            with open(prompt_path, 'r') as f:
                system_prompt_template = f.read()
        except Exception as e:
            self.logger.error(f"Could not load prompt file: {e}")
            system_prompt_template = """You are an elite Penetration Tester Agent within an autonomous enterprise security team.

YOUR CAPABILITIES:
Skills: {skills}
Completed Assessments: {completed_assessments}

SECURITY STANDARDS:
- Follow OWASP Top 10 guidelines
- Adhere to ethical hacking principles
- Document all findings with severity ratings
- Provide actionable remediation steps
- Maintain strict confidentiality

AVAILABLE CONTEXT:
[Retrieved Security Knowledge]
{security_knowledge_context}

[Memory of Previous Assessments]
{previous_context}

[Additional Context for Current Mission]
{additional_context}

YOUR CURRENT MISSION:
Task: {task}

INSTRUCTIONS:
1. Analyze the security assessment requirements
2. Identify potential attack vectors and vulnerabilities
3. Provide detailed security findings with risk ratings
4. Include specific remediation recommendations
5. Return comprehensive security assessment report"""

        # --- 4. Assemble the Final Prompt ---
        full_prompt = system_prompt_template.format(
            skills=', '.join(self.config.get('skills', [])),
            completed_assessments=len(previous_assessments),
            security_knowledge_context=security_context or "No specific security context found.",
            previous_context=json.dumps(self.get_state('context_memory', {}), indent=2),
            additional_context=json.dumps(context, indent=2) if context else "None",
            task=prompt
        )
        
        return full_prompt

    def _process_response(self, response: str) -> dict:
        """
        Processes the raw LLM response into a structured security assessment report.
        """
        self.logger.info("Processing security assessment response.")
        
        # Extract key security components from response
        assessment_summary = response[:500] + "..." if len(response) > 500 else response
        
        result = {
            'agent_type': 'PenetrationTester',
            'task_id': f"security_assessment_{self.task_count}",
            'timestamp': self.last_activity.isoformat(),
            'summary': assessment_summary,
            'full_response': response,
            'assessment_type': 'penetration_test',
            'vulnerabilities': self._extract_vulnerabilities(response),
            'risk_rating': self._calculate_risk_rating(response),
            'remediation_steps': self._extract_remediation_steps(response)
        }
        
        self._update_project_memory(result)
        
        # Generate security report using file_write tool
        file_tool = self.get_tool("file_write")
        if file_tool:
            report_path = f"data/agent_outputs/security_assessment_{self.task_count}.md"
            report_content = f"""# Security Assessment Report
**Generated by**: PenetrationTester (Architecture 3.0)
**Assessment ID**: {result['task_id']}
**Timestamp**: {result['timestamp']}
**Risk Rating**: {result['risk_rating']}

## Executive Summary
{assessment_summary}

## Identified Vulnerabilities
{self._format_vulnerabilities(result['vulnerabilities'])}

## Remediation Steps
{self._format_remediation_steps(result['remediation_steps'])}

## Full Assessment Details
{response}

---
*This assessment was conducted by an autonomous security agent following OWASP guidelines and ethical hacking principles.*
"""
            save_result = file_tool(path=report_path, content=report_content)
            if save_result.get('success'):
                self.logger.info(f"Security assessment report saved to {report_path}")
                result['report_path'] = report_path

        return result

    def _extract_vulnerabilities(self, response: str) -> list:
        """Extract identified vulnerabilities from the assessment"""
        vulnerabilities = []
        lines = response.split('\n')
        
        vulnerability_keywords = ['vulnerability', 'exploit', 'weakness', 'flaw', 'security issue']
        
        for line in lines:
            if any(keyword in line.lower() for keyword in vulnerability_keywords):
                vulnerabilities.append({
                    'description': line.strip(),
                    'severity': self._assess_severity(line),
                    'category': self._categorize_vulnerability(line)
                })
        
        return vulnerabilities[:10]  # Top 10 vulnerabilities

    def _calculate_risk_rating(self, response: str) -> str:
        """Calculate overall risk rating based on assessment"""
        high_risk_keywords = ['critical', 'severe', 'high risk', 'exploit', 'compromise']
        medium_risk_keywords = ['moderate', 'medium', 'concern', 'issue']
        
        high_count = sum(1 for keyword in high_risk_keywords if keyword in response.lower())
        medium_count = sum(1 for keyword in medium_risk_keywords if keyword in response.lower())
        
        if high_count >= 3:
            return "HIGH"
        elif high_count >= 1 or medium_count >= 5:
            return "MEDIUM"
        else:
            return "LOW"

    def _assess_severity(self, vulnerability_text: str) -> str:
        """Assess severity of individual vulnerability"""
        if any(word in vulnerability_text.lower() for word in ['critical', 'severe', 'exploit']):
            return "CRITICAL"
        elif any(word in vulnerability_text.lower() for word in ['high', 'serious', 'major']):
            return "HIGH"
        elif any(word in vulnerability_text.lower() for word in ['medium', 'moderate']):
            return "MEDIUM"
        else:
            return "LOW"

    def _categorize_vulnerability(self, vulnerability_text: str) -> str:
        """Categorize vulnerability type"""
        categories = {
            'injection': ['sql', 'injection', 'xss', 'script'],
            'authentication': ['auth', 'login', 'password', 'session'],
            'authorization': ['access', 'permission', 'privilege'],
            'configuration': ['config', 'setting', 'default'],
            'encryption': ['crypto', 'ssl', 'tls', 'encryption']
        }
        
        text_lower = vulnerability_text.lower()
        for category, keywords in categories.items():
            if any(keyword in text_lower for keyword in keywords):
                return category
        return 'general'

    def _extract_remediation_steps(self, response: str) -> list:
        """Extract remediation recommendations"""
        remediation_steps = []
        lines = response.split('\n')
        
        for line in lines:
            if any(keyword in line.lower() for keyword in ['fix', 'patch', 'update', 'remediate', 'mitigate']):
                remediation_steps.append(line.strip())
        
        return remediation_steps[:8]  # Top 8 remediation steps

    def _format_vulnerabilities(self, vulnerabilities: list) -> str:
        """Format vulnerabilities for report"""
        if not vulnerabilities:
            return "No critical vulnerabilities identified."
        
        formatted = ""
        for i, vuln in enumerate(vulnerabilities, 1):
            formatted += f"{i}. **{vuln['severity']}** - {vuln['description']} (Category: {vuln['category']})\n"
        return formatted

    def _format_remediation_steps(self, steps: list) -> str:
        """Format remediation steps for report"""
        if not steps:
            return "No specific remediation steps identified."
        
        formatted = ""
        for i, step in enumerate(steps, 1):
            formatted += f"{i}. {step}\n"
        return formatted

    def _update_project_memory(self, result: dict):
        """Updates the agent's persistent state with assessment details."""
        assessments = self.get_state('completed_assessments', [])
        assessments.append({
            'task_id': result['task_id'],
            'timestamp': result['timestamp'],
            'assessment_type': result['assessment_type'],
            'risk_rating': result['risk_rating'],
            'vulnerability_count': len(result['vulnerabilities'])
        })
        
        # Keep last 15 assessments
        if len(assessments) > 15:
            assessments = assessments[-15:]
            
        self.update_state('completed_assessments', assessments)
        self.update_state('total_assessments_completed', len(assessments))
        
        # Update context memory for future assessments
        context_memory = {
            'last_assessment_type': result['assessment_type'],
            'recent_risk_level': result['risk_rating'],
            'common_vulnerabilities': [v['category'] for v in result['vulnerabilities'][:3]]
        }
        self.update_state('context_memory', context_memory)
        
        self.logger.info(f"Security agent memory updated. Total assessments: {len(assessments)}")
