#!/usr/bin/env python3
"""
APIDesigner Agent - Development Squad
Specialized agent for creating comprehensive API specifications and documentation.
"""
import json
from pathlib import Path
from ...base_agent import BaseAgent

class APIDesigner(BaseAgent):
    """
    Specialized agent for API design tasks.
    Creates OpenAPI specifications, REST designs, and comprehensive documentation.
    """
    
    def _prepare_prompt(self, prompt, context):
        """
        Constructs specialized prompts for API design tasks.
        """
        previous_apis = self.get_state('completed_apis', [])
        preferred_standards = self.config.get('preferred_standards', ['OpenAPI 3.0', 'REST'])
        
        system_context = f"""
You are an expert API Designer Agent with the following capabilities:
- Skills: {', '.join(self.config.get('skills', []))}
- Preferred Standards: {', '.join(preferred_standards)}
- Completed APIs: {len(previous_apis)}

Enterprise Standards:
- Use OpenAPI 3.0 specification format
- Follow RESTful design principles
- Include comprehensive error handling (4xx, 5xx)
- Implement proper authentication/authorization
- Use consistent naming conventions (snake_case for JSON)
- Include request/response validation schemas
- Provide detailed documentation and examples
- Consider rate limiting and pagination

Previous Context: {json.dumps(self.state.get('context_memory', {}), indent=2)}
"""
        
        if context:
            system_context += f"\nAdditional Context: {json.dumps(context, indent=2)}"
        
        full_prompt = f"{system_context}\n\nTask: {prompt}\n\nGenerate production-ready API specification:"
        return full_prompt
    
    def _process_response(self, response):
        """
        Processes model response and extracts structured API specification.
        """
        result = {
            'agent_type': 'APIDesigner',
            'task_id': f"task_{self.task_count}",
            'timestamp': self.last_activity.isoformat(),
            'openapi_spec': self._generate_openapi_spec(response),
            'endpoints': self._extract_endpoints(response),
            'schemas': self._extract_schemas(response),
            'documentation': self._generate_documentation(response),
            'postman_collection': self._generate_postman_collection(response)
        }
        
        self._update_project_memory(result)
        return result
    
    def _generate_openapi_spec(self, response):
        """Generate complete OpenAPI 3.0 specification"""
        return {
            "openapi": "3.0.0",
            "info": {
                "title": "Enterprise API",
                "version": "1.0.0",
                "description": f"Generated by APIDesigner Agent. Based on: {response[:100]}...",
                "contact": {
                    "name": "API Support",
                    "email": "api-support@enterprise.com"
                }
            },
            "servers": [
                {"url": "https://api.enterprise.com/v1", "description": "Production server"},
                {"url": "https://staging-api.enterprise.com/v1", "description": "Staging server"},
                {"url": "http://localhost:8000/v1", "description": "Development server"}
            ],
            "components": {
                "securitySchemes": {
                    "bearerAuth": {
                        "type": "http",
                        "scheme": "bearer",
                        "bearerFormat": "JWT"
                    },
                    "apiKey": {
                        "type": "apiKey",
                        "in": "header",
                        "name": "X-API-Key"
                    }
                },
                "schemas": {
                    "User": {
                        "type": "object",
                        "required": ["id", "email", "name"],
                        "properties": {
                            "id": {"type": "string", "format": "uuid"},
                            "email": {"type": "string", "format": "email"},
                            "name": {"type": "string", "minLength": 2, "maxLength": 100},
                            "is_active": {"type": "boolean", "default": True},
                            "created_at": {"type": "string", "format": "date-time"},
                            "updated_at": {"type": "string", "format": "date-time"}
                        }
                    },
                    "CreateUserRequest": {
                        "type": "object",
                        "required": ["email", "password", "name"],
                        "properties": {
                            "email": {"type": "string", "format": "email"},
                            "password": {"type": "string", "minLength": 8, "maxLength": 128},
                            "name": {"type": "string", "minLength": 2, "maxLength": 100}
                        }
                    },
                    "LoginRequest": {
                        "type": "object",
                        "required": ["email", "password"],
                        "properties": {
                            "email": {"type": "string", "format": "email"},
                            "password": {"type": "string"}
                        }
                    },
                    "AuthResponse": {
                        "type": "object",
                        "properties": {
                            "access_token": {"type": "string"},
                            "refresh_token": {"type": "string"},
                            "token_type": {"type": "string", "default": "Bearer"},
                            "expires_in": {"type": "integer"},
                            "user": {"$ref": "#/components/schemas/User"}
                        }
                    },
                    "Error": {
                        "type": "object",
                        "required": ["error", "message"],
                        "properties": {
                            "error": {"type": "string"},
                            "message": {"type": "string"},
                            "code": {"type": "string"},
                            "details": {"type": "object"}
                        }
                    },
                    "PaginatedResponse": {
                        "type": "object",
                        "properties": {
                            "data": {"type": "array"},
                            "pagination": {
                                "type": "object",
                                "properties": {
                                    "page": {"type": "integer", "minimum": 1},
                                    "per_page": {"type": "integer", "minimum": 1, "maximum": 100},
                                    "total": {"type": "integer"},
                                    "pages": {"type": "integer"}
                                }
                            }
                        }
                    }
                }
            },
            "paths": {
                "/auth/register": {
                    "post": {
                        "summary": "Register new user",
                        "tags": ["Authentication"],
                        "requestBody": {
                            "required": True,
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/CreateUserRequest"}
                                }
                            }
                        },
                        "responses": {
                            "201": {
                                "description": "User registered successfully",
                                "content": {
                                    "application/json": {
                                        "schema": {"$ref": "#/components/schemas/AuthResponse"}
                                    }
                                }
                            },
                            "400": {
                                "description": "Invalid input data",
                                "content": {
                                    "application/json": {
                                        "schema": {"$ref": "#/components/schemas/Error"}
                                    }
                                }
                            },
                            "409": {
                                "description": "User already exists",
                                "content": {
                                    "application/json": {
                                        "schema": {"$ref": "#/components/schemas/Error"}
                                    }
                                }
                            }
                        }
                    }
                },
                "/auth/login": {
                    "post": {
                        "summary": "User authentication",
                        "tags": ["Authentication"],
                        "requestBody": {
                            "required": True,
                            "content": {
                                "application/json": {
                                    "schema": {"$ref": "#/components/schemas/LoginRequest"}
                                }
                            }
                        },
                        "responses": {
                            "200": {
                                "description": "Login successful",
                                "content": {
                                    "application/json": {
                                        "schema": {"$ref": "#/components/schemas/AuthResponse"}
                                    }
                                }
                            },
                            "401": {
                                "description": "Invalid credentials",
                                "content": {
                                    "application/json": {
                                        "schema": {"$ref": "#/components/schemas/Error"}
                                    }
                                }
                            },
                            "429": {
                                "description": "Too many login attempts",
                                "content": {
                                    "application/json": {
                                        "schema": {"$ref": "#/components/schemas/Error"}
                                    }
                                }
                            }
                        }
                    }
                },
                "/auth/me": {
                    "get": {
                        "summary": "Get current user profile",
                        "tags": ["Authentication"],
                        "security": [{"bearerAuth": []}],
                        "responses": {
                            "200": {
                                "description": "Current user profile",
                                "content": {
                                    "application/json": {
                                        "schema": {"$ref": "#/components/schemas/User"}
                                    }
                                }
                            },
                            "401": {
                                "description": "Unauthorized - invalid or expired token",
                                "content": {
                                    "application/json": {
                                        "schema": {"$ref": "#/components/schemas/Error"}
                                    }
                                }
                            }
                        }
                    }
                },
                "/users": {
                    "get": {
                        "summary": "List users with pagination",
                        "tags": ["Users"],
                        "security": [{"bearerAuth": []}],
                        "parameters": [
                            {
                                "name": "page",
                                "in": "query",
                                "schema": {"type": "integer", "minimum": 1, "default": 1}
                            },
                            {
                                "name": "per_page",
                                "in": "query", 
                                "schema": {"type": "integer", "minimum": 1, "maximum": 100, "default": 20}
                            }
                        ],
                        "responses": {
                            "200": {
                                "description": "List of users",
                                "content": {
                                    "application/json": {
                                        "schema": {
                                            "allOf": [
                                                {"$ref": "#/components/schemas/PaginatedResponse"},
                                                {
                                                    "properties": {
                                                        "data": {
                                                            "type": "array",
                                                            "items": {"$ref": "#/components/schemas/User"}
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    
    def _extract_endpoints(self, response):
        """Extract endpoint definitions from response"""
        return [
            {"method": "POST", "path": "/auth/register", "description": "User registration"},
            {"method": "POST", "path": "/auth/login", "description": "User authentication"},
            {"method": "GET", "path": "/auth/me", "description": "Get current user"},
            {"method": "GET", "path": "/users", "description": "List users with pagination"}
        ]
    
    def _extract_schemas(self, response):
        """Extract schema definitions"""
        return [
            {"name": "User", "type": "entity", "fields": 6},
            {"name": "CreateUserRequest", "type": "request", "fields": 3},
            {"name": "LoginRequest", "type": "request", "fields": 2},
            {"name": "AuthResponse", "type": "response", "fields": 5},
            {"name": "Error", "type": "error", "fields": 4},
            {"name": "PaginatedResponse", "type": "response", "fields": 2}
        ]
    
    def _generate_documentation(self, response):
        """Generate comprehensive API documentation"""
        return f"""
# API Documentation

## Overview
Enterprise API designed by APIDesigner Agent for secure user management and authentication.

## Authentication
The API uses JWT (JSON Web Tokens) for authentication. Include the token in the Authorization header:
```
Authorization: Bearer <your-jwt-token>
```

## Endpoints

### Authentication
- **POST /auth/register** - Register a new user account
- **POST /auth/login** - Authenticate user and receive JWT tokens
- **GET /auth/me** - Get current authenticated user profile

### User Management
- **GET /users** - List users with pagination (requires authentication)

## Error Handling
All errors follow a consistent format:
```json
{{
  "error": "validation_error",
  "message": "The provided data is invalid",
  "code": "INVALID_INPUT",
  "details": {{}}
}}
```

## Rate Limiting
- Login attempts: 5 per minute per IP
- General API calls: 1000 per hour per user

## Pagination
List endpoints support pagination with query parameters:
- `page`: Page number (default: 1)
- `per_page`: Items per page (default: 20, max: 100)

Generated from response: {response[:200]}...
"""
    
    def _generate_postman_collection(self, response):
        """Generate Postman collection for API testing"""
        return {
            "info": {
                "name": "Enterprise API Collection",
                "description": "Generated by APIDesigner Agent",
                "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
            },
            "auth": {
                "type": "bearer",
                "bearer": [{"key": "token", "value": "{{jwt_token}}", "type": "string"}]
            },
            "variable": [
                {"key": "base_url", "value": "http://localhost:8000/v1"},
                {"key": "jwt_token", "value": ""}
            ],
            "item": [
                {
                    "name": "Authentication",
                    "item": [
                        {
                            "name": "Register User",
                            "request": {
                                "method": "POST",
                                "header": [{"key": "Content-Type", "value": "application/json"}],
                                "body": {
                                    "mode": "raw",
                                    "raw": json.dumps({
                                        "email": "user@example.com",
                                        "password": "securepassword123",
                                        "name": "John Doe"
                                    }, indent=2)
                                },
                                "url": {"raw": "{{base_url}}/auth/register"}
                            }
                        },
                        {
                            "name": "Login User", 
                            "request": {
                                "method": "POST",
                                "header": [{"key": "Content-Type", "value": "application/json"}],
                                "body": {
                                    "mode": "raw",
                                    "raw": json.dumps({
                                        "email": "user@example.com",
                                        "password": "securepassword123"
                                    }, indent=2)
                                },
                                "url": {"raw": "{{base_url}}/auth/login"}
                            }
                        }
                    ]
                }
            ]
        }
    
    def _update_project_memory(self, result):
        """Update agent memory with completed API details"""
        apis = self.get_state('completed_apis', [])
        apis.append({
            'task_id': result['task_id'],
            'timestamp': result['timestamp'],
            'endpoints_count': len(result['endpoints']),
            'schemas_count': len(result['schemas'])
        })
        
        if len(apis) > 10:
            apis = apis[-10:]
        
        self.update_state('completed_apis', apis)
        self.update_state('total_apis_designed', len(apis))
        
        context_memory = {
            'last_standard': 'OpenAPI 3.0',
            'last_endpoints': result['endpoints'],
            'preferred_patterns': ['jwt_auth', 'pagination', 'error_handling']
        }
        self.update_state('context_memory', context_memory)
