#!/usr/bin/env python3
"""
BackendDeveloper Agent - Development Squad
Specialized agent for generating FastAPI/Flask backends from specifications.
"""
import json
from pathlib import Path
from ...base_agent import BaseAgent

class BackendDeveloper(BaseAgent):
    """
    Specialized agent for backend development tasks.
    Generates FastAPI/Flask backends, API designs, and database integrations.
    """
    
    def _prepare_prompt(self, prompt, context):
        """
        Constructs specialized prompts for backend development tasks.
        Includes agent expertise, context, and enterprise standards.
        """
        # Get agent's specialized knowledge from state
        previous_projects = self.get_state('completed_projects', [])
        preferred_frameworks = self.config.get('preferred_frameworks', ['FastAPI', 'Flask'])
        
        # Build context-aware prompt
        system_context = f"""
You are an expert Backend Developer Agent with the following capabilities:
- Skills: {', '.join(self.config.get('skills', []))}
- Preferred Frameworks: {', '.join(preferred_frameworks)}
- Completed Projects: {len(previous_projects)}

Enterprise Standards:
- Use type hints and Pydantic models
- Implement proper error handling and logging
- Follow RESTful API design principles
- Include comprehensive docstrings
- Use dependency injection patterns

Previous Context: {json.dumps(self.state.get('context_memory', {}), indent=2)}
"""
        
        # Add any provided context
        if context:
            system_context += f"\nAdditional Context: {json.dumps(context, indent=2)}"
        
        full_prompt = f"{system_context}\n\nTask: {prompt}\n\nGenerate production-ready backend code:"
        
        self.logger.debug(f"Prepared prompt length: {len(full_prompt)} characters")
        return full_prompt
    
    def _process_response(self, response):
        """
        Processes model response and extracts structured backend code.
        Returns formatted result with code, documentation, and metadata.
        """
        # For Step 1, we'll process the mock response
        # In Step 2, this will parse actual model output for code blocks, tests, etc.
        
        # Extract or generate code structure
        result = {
            'agent_type': 'BackendDeveloper',
            'task_id': f"task_{self.task_count}",
            'timestamp': self.last_activity.isoformat(),
            'code': self._extract_code_from_response(response),
            'documentation': self._extract_documentation(response),
            'api_endpoints': self._extract_api_endpoints(response),
            'dependencies': self._extract_dependencies(response),
            'tests': self._generate_tests(response)
        }
        
        # Update agent memory with project details
        self._update_project_memory(result)
        
        # Use file_write tool if available
        file_tool = self.get_tool('file_write')
        if file_tool:
            self.logger.info("File write tool available for code generation")
        
        return result
    
    def _extract_code_from_response(self, response):
        """Extract main application code from model response"""
        # Mock implementation for Step 1
        return f"""
# Generated FastAPI Backend
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import logging

app = FastAPI(title="Enterprise API", version="1.0.0")

class ItemModel(BaseModel):
    name: str
    description: str

@app.get("/health")
async def health_check():
    return {{"status": "healthy", "agent": "BackendDeveloper"}}

@app.post("/items/")
async def create_item(item: ItemModel):
    # Generated from: {response[:100]}...
    return {{"message": "Item created", "item": item}}

# Response was: {response}
"""
    
    def _extract_documentation(self, response):
        """Extract API documentation from response"""
        return f"""
# Backend API Documentation

## Overview
Generated by BackendDeveloper Agent

## Endpoints
- GET /health - Health check endpoint
- POST /items/ - Create new item

## Models
- ItemModel: Basic item structure

Generated from response: {response[:200]}...
"""
    
    def _extract_api_endpoints(self, response):
        """Extract API endpoint definitions"""
        return [
            {"method": "GET", "path": "/health", "description": "Health check"},
            {"method": "POST", "path": "/items/", "description": "Create item"}
        ]
    
    def _extract_dependencies(self, response):
        """Extract required dependencies"""
        return [
            "fastapi>=0.104.0",
            "pydantic>=2.0.0",
            "uvicorn>=0.24.0"
        ]
    
    def _generate_tests(self, response):
        """Generate test code for the backend"""
        return f"""
# Generated Tests
import pytest
from fastapi.testclient import TestClient
from main import app

client = TestClient(app)

def test_health_check():
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "healthy"

def test_create_item():
    item_data = {{"name": "test", "description": "test item"}}
    response = client.post("/items/", json=item_data)
    assert response.status_code == 200

# Based on: {response[:100]}...
"""
    
    def _update_project_memory(self, result):
        """Update agent memory with completed project details"""
        projects = self.get_state('completed_projects', [])
        projects.append({
            'task_id': result['task_id'],
            'timestamp': result['timestamp'],
            'endpoints_count': len(result['api_endpoints']),
            'dependencies_count': len(result['dependencies'])
        })
        
        # Keep only last 10 projects in memory
        if len(projects) > 10:
            projects = projects[-10:]
        
        self.update_state('completed_projects', projects)
        self.update_state('total_apis_created', len(projects))
        
        # Update context memory for future tasks
        context_memory = {
            'last_framework': 'FastAPI',
            'last_endpoints': result['api_endpoints'],
            'preferred_patterns': ['dependency_injection', 'pydantic_models']
        }
        self.update_state('context_memory', context_memory)
