#!/usr/bin/env python3
"""
FrontendDeveloper Agent - Development Squad
Specialized agent for generating React/Vue frontends from specifications.
"""
import json
from pathlib import Path
from ...base_agent import BaseAgent

class FrontendDeveloper(BaseAgent):
    """
    Specialized agent for frontend development tasks.
    Generates React/Vue frontends, component libraries, and responsive designs.
    """
    
    def _prepare_prompt(self, prompt, context):
        """
        Constructs specialized prompts for frontend development tasks.
        """
        previous_projects = self.get_state('completed_projects', [])
        preferred_frameworks = self.config.get('preferred_frameworks', ['React', 'Vue.js'])
        
        system_context = f"""
You are an expert Frontend Developer Agent with the following capabilities:
- Skills: {', '.join(self.config.get('skills', []))}
- Preferred Frameworks: {', '.join(preferred_frameworks)}
- Completed Projects: {len(previous_projects)}

Enterprise Standards:
- Use TypeScript for type safety
- Implement responsive design with Tailwind CSS
- Follow component composition patterns
- Include proper error boundaries
- Use modern React hooks and patterns
- Implement accessibility (a11y) standards

Previous Context: {json.dumps(self.state.get('context_memory', {}), indent=2)}
"""
        
        if context:
            system_context += f"\nAdditional Context: {json.dumps(context, indent=2)}"
        
        full_prompt = f"{system_context}\n\nTask: {prompt}\n\nGenerate production-ready frontend code:"
        return full_prompt
    
    def _process_response(self, response):
        """
        Processes model response and extracts structured frontend code.
        """
        result = {
            'agent_type': 'FrontendDeveloper',
            'task_id': f"task_{self.task_count}",
            'timestamp': self.last_activity.isoformat(),
            'code': self._extract_code_from_response(response),
            'components': self._extract_components(response),
            'styles': self._extract_styles(response),
            'dependencies': self._extract_dependencies(response),
            'tests': self._generate_tests(response)
        }
        
        self._update_project_memory(result)
        return result
    
    def _extract_code_from_response(self, response):
        """Extract main React/Vue code from model response"""
        return f"""
// Generated React Frontend
import React, {{ useState, useEffect }} from 'react';
import {{ BrowserRouter as Router, Routes, Route, Navigate }} from 'react-router-dom';

const App = () => {{
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {{
    // Check authentication status
    const token = localStorage.getItem('token');
    if (token) {{
      // Validate token and set user
      setUser({{ authenticated: true }});
    }}
    setLoading(false);
  }}, []);

  if (loading) return <div className="flex justify-center items-center h-screen">Loading...</div>;

  return (
    <Router>
      <div className="min-h-screen bg-gray-50">
        <Routes>
          <Route path="/login" element={{user ? <Navigate to="/dashboard" /> : <LoginForm />}} />
          <Route path="/dashboard" element={{user ? <Dashboard /> : <Navigate to="/login" />}} />
          <Route path="/" element={{<Navigate to={{user ? "/dashboard" : "/login"}} />}} />
        </Routes>
      </div>
    </Router>
  );
}};

const LoginForm = () => (
  <div className="flex justify-center items-center h-screen">
    <form className="bg-white p-8 rounded-lg shadow-md w-96">
      <h2 className="text-2xl font-bold mb-6">Login</h2>
      <input type="email" placeholder="Email" className="w-full p-3 border rounded mb-4" />
      <input type="password" placeholder="Password" className="w-full p-3 border rounded mb-4" />
      <button className="w-full bg-blue-500 text-white p-3 rounded hover:bg-blue-600">
        Login
      </button>
    </form>
  </div>
);

const Dashboard = () => (
  <div className="p-8">
    <h1 className="text-3xl font-bold mb-6">Dashboard</h1>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
      <div className="bg-white p-6 rounded-lg shadow">
        <h3 className="text-xl font-semibold">Welcome</h3>
        <p>Frontend generated by FrontendDeveloper Agent</p>
      </div>
    </div>
  </div>
);

export default App;

// Response was: {response[:100]}...
"""
    
    def _extract_components(self, response):
        """Extract React components from response"""
        return [
            {"name": "App", "type": "main", "description": "Main application component"},
            {"name": "LoginForm", "type": "form", "description": "User authentication form"},
            {"name": "Dashboard", "type": "page", "description": "User dashboard page"}
        ]
    
    def _extract_styles(self, response):
        """Extract CSS/Tailwind styles"""
        return {
            "framework": "Tailwind CSS",
            "theme": "modern",
            "responsive": True,
            "classes_used": ["flex", "justify-center", "items-center", "bg-gray-50", "rounded-lg", "shadow-md"]
        }
    
    def _extract_dependencies(self, response):
        """Extract required dependencies"""
        return [
            "react>=18.0.0",
            "react-dom>=18.0.0",
            "react-router-dom>=6.0.0",
            "tailwindcss>=3.0.0",
            "axios>=1.0.0"
        ]
    
    def _generate_tests(self, response):
        """Generate test code for the frontend"""
        return f"""
// Generated Tests
import {{ render, screen, fireEvent }} from '@testing-library/react';
import {{ BrowserRouter }} from 'react-router-dom';
import App from './App';

const renderWithRouter = (component) => {{
  return render(
    <BrowserRouter>
      {{component}}
    </BrowserRouter>
  );
}};

test('renders login form when not authenticated', () => {{
  renderWithRouter(<App />);
  expect(screen.getByText('Login')).toBeInTheDocument();
}});

test('login form accepts input', () => {{
  renderWithRouter(<App />);
  const emailInput = screen.getByPlaceholderText('Email');
  fireEvent.change(emailInput, {{ target: {{ value: 'test@example.com' }} }});
  expect(emailInput.value).toBe('test@example.com');
}});

// Based on: {response[:100]}...
"""
    
    def _update_project_memory(self, result):
        """Update agent memory with completed project details"""
        projects = self.get_state('completed_projects', [])
        projects.append({
            'task_id': result['task_id'],
            'timestamp': result['timestamp'],
            'components_count': len(result['components']),
            'framework': result['styles']['framework']
        })
        
        if len(projects) > 10:
            projects = projects[-10:]
        
        self.update_state('completed_projects', projects)
        self.update_state('total_frontends_created', len(projects))
        
        context_memory = {
            'last_framework': 'React',
            'last_components': result['components'],
            'preferred_patterns': ['hooks', 'functional_components', 'tailwind_css']
        }
        self.update_state('context_memory', context_memory)
